name: Deploy Node Application

on: 
  push:
    branches:
      -mern-ec2-docker


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v4
      - name: Log in to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t unixisuru/nodejs-app .
      - name: Publish Image to docker hub
        run: docker push unixisuru/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
     - name: Pull image from docker hub
       run: docker pull unixisuru/nodejs-app:latest
     - name: Run docker container
       run: docker run -d -p 3000:3000 --name nodejs-app-container -e MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}' unixisuru/nodejs-app
